extends RefCounted

const ArenaScript = preload("res://scripts/ui/ArenaView.gd")
const StateScript = preload("res://scripts/core/SurvivorState.gd")
const MetricsScript = preload("res://scripts/performance/Phase6MetricsSystem.gd")

func run(t) -> void:
	var state = StateScript.new()
	state.start_new_run(60606)
	var arena = ArenaScript.new()
	arena.size = Vector2(1280, 720)
	arena.bind_state(state)
	var metrics = MetricsScript.new()
	metrics.configure(true)
	arena.set_phase6_metrics(metrics)
	var tile_size := float(state.map_data.get("tile_size", 64.0))
	var first_key := arena._terrain_key(tile_size)
	arena._rebuild_terrain_cache(tile_size, first_key)
	var first_cache_size: int = arena.terrain_draw_cache.size()
	t.assert_true(first_cache_size > 0, "static terrain cache should contain visible terrain commands")
	t.assert_eq(arena.terrain_cache_rebuild_count, 1, "initial cache rebuild should be counted once")
	var same_key := arena._terrain_key(tile_size)
	if same_key != arena.terrain_cache_key:
		arena._rebuild_terrain_cache(tile_size, same_key)
	t.assert_eq(arena.terrain_cache_rebuild_count, 1, "same camera/map signature should not force another static rebuild")
	state.camera_position += Vector2(tile_size * 2.0, 0.0)
	var moved_key := arena._terrain_key(tile_size)
	t.assert_true(moved_key != first_key, "camera cell movement should change the static cache key")
	arena.size = Vector2(720, 1280)
	var resized_key: String = arena._terrain_key(tile_size)
	t.assert_true(resized_key != moved_key, "viewport resize or orientation change should invalidate the static cache signature")
	var original_renderer: String = String(ProjectSettings.get_setting("rendering/renderer/rendering_method", "gl_compatibility"))
	ProjectSettings.set_setting("rendering/renderer/rendering_method", "mobile")
	var renderer_key: String = arena._terrain_key(tile_size)
	t.assert_true(renderer_key != resized_key, "renderer changes should invalidate the static cache signature")
	ProjectSettings.set_setting("rendering/renderer/rendering_method", original_renderer)
	var original_quality: String = String(arena.environment_visual_system.quality_config.get("default_profile", "medium"))
	arena.environment_visual_system.quality_config["default_profile"] = "low"
	var quality_key: String = arena._terrain_key(tile_size)
	t.assert_true(quality_key != resized_key, "quality profile changes should invalidate the static cache signature")
	arena.environment_visual_system.quality_config["default_profile"] = original_quality
	arena.invalidate_static_cache("test_resize")
	t.assert_eq(arena.terrain_cache_key, "", "explicit invalidation should clear the cache key")
	t.assert_eq(arena.terrain_draw_cache.size(), 0, "explicit invalidation should clear cached draw commands")
	var boundary: Array = state.map_data.get("boundary_cells", [])
	boundary.append("999:999")
	state.map_data["boundary_cells"] = boundary
	var map_key: String = arena._terrain_key(tile_size)
	t.assert_true(map_key != moved_key, "map cell count changes should invalidate the static cache signature")
	t.assert_true(int(metrics.snapshot().counters.get("static_cache_invalidations", 0)) >= 1, "cache invalidations should be visible in QA metrics")
	arena.free()
